### ISSUE TITLE
Schema change column added, sync, rerun, still new column not showing 

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/webapp#1052]
It worked later but should look into this.

**Comment by fatchat** [comment]
this is as per the schema-change-detection spec, new columns should NOT appear unless the schema changes are approved. airbyte does it this way to keep pipelines from breaking when sources are modified

i understand if there is a user journey which makes this awkward, and then we can design a fix to that journey. but as stated this is desired behavior

**Comment by nairabhishek73** [comment]
Yes, did not mention here but refreshed schema, approved changes, still did not show up.

**Comment by fatchat** [comment]
ok then this is a schema-change bug. let us know 
- org
- source
- connection
please

**Comment by nairabhishek73** [comment]
- Adhyayan
- Google sheets Domain1and6_Tripura, Domain1_AP
- DomainTripura1and6_Conn, Domain1_AP

**Comment by mdshamoon** [comment]
There are two issues that I was able to find:

- When we press reset schema button the task id is not generated immedialtely and gives an error. But if you refresh the page it shows pending actions. Added a fix for it here: https://github.com/DalgoT4D/DDP_backend/pull/818

- Running sync button just after approving the changes gives an error in prefect. But the sync is always successful in airbyte. 
Also the sync works fine after the first time

Error that we get in prefect

```
Encountered exception during execution:
Traceback (most recent call last):
  File "/Users/mdshamoon/Projects/prefect-proxy/venv/lib/python3.10/site-packages/prefect_airbyte/client.py", line 155, in trigger_manual_sync_connection
    response.raise_for_status()
  File "/Users/mdshamoon/Projects/prefect-proxy/venv/lib/python3.10/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '409 Conflict' for url 'http://localhost:8000/api/v1/connections/sync/'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mdshamoon/Projects/prefect-proxy/venv/lib/python3.10/site-packages/prefect/engine.py", line 877, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/Users/mdshamoon/Projects/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/Users/mdshamoon/Projects/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/Users/mdshamoon/Projects/prefect-proxy/venv/lib/python3.10/site-packages/prefect_airbyte/flows.py", line 57, in run_connection_sync
    airbyte_sync = await task(airbyte_connection.trigger.aio)(airbyte_connection)
  File "/Users/mdshamoon/Projects/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/api.py", line 150, in wait_for_call_in_loop_thread
    return call.result()
  File "/Users/mdshamoon/Projects/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
  File "/Users/mdshamoon/Projects/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
  File "/Users/mdshamoon/.pyenv/versions/3.10.14/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/mdshamoon/Projects/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/Users/mdshamoon/Projects/prefect-proxy/venv/lib/python3.10/site-packages/prefect/engine.py", line 1555, in get_task_call_return_value
    return await future._result()
  File "/Users/mdshamoon/Projects/prefect-proxy/venv/lib/python3.10/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "/Users/mdshamoon/Projects/prefect-proxy/venv/lib/python3.10/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/Users/mdshamoon/Projects/prefect-proxy/venv/lib/python3.10/site-packages/prefect/engine.py", line 2103, in orchestrate_task_run
    result = await call.aresult()
  File "/Users/mdshamoon/Projects/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/Users/mdshamoon/Projects/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/Users/mdshamoon/Projects/prefect-proxy/venv/lib/python3.10/site-packages/prefect_airbyte/connections.py", line 378, in trigger
    ) = await airbyte_client.trigger_manual_sync_connection(
  File "/Users/mdshamoon/Projects/prefect-proxy/venv/lib/python3.10/site-packages/prefect_airbyte/client.py", line 167, in trigger_manual_sync_connection
    raise err.AirbyteServerNotHealthyException() from e
prefect_airbyte.exceptions.AirbyteServerNotHealthyException
```

**Comment by fatchat** [comment]
@Ishankoradia please see Shamoon's commenet above re: the Airbyte `409` , will this be fixed by your work this week
