### ISSUE TITLE
Materialized model I'm not able to create 

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/webapp#628]
**Describe the bug**
I have to create a model to do the coalesce and it gives me this materliaze view of the table. 

1. But when I run it its giving me this error 
2. No one will understand in ngo space "please click run to your materialized model". "please click run to create your new table or model"

<img width="969" alt="Screenshot 2024-03-22 at 10 18 18 AM" src="https://github.com/DalgoT4D/webapp/assets/9019958/8cb5421e-6b37-43d2-8e80-d8271c900a35">

To the admins of Siddhant_test [STAGING],

This is an automated notification from Dalgo [STAGING].
```

Flow run id: 4e6f6136-0e2f-49a0-9e9b-3146f8c64a49
Logs:
Downloading flow code from storage at '/home/ddp/prefect-proxy'
Created task run 'dbtjob_v1-0' for task 'dbtjob_v1'
Executing 'dbtjob_v1-0' immediately...
PID 885571 triggered with 1 commands running inside the PosixPath('/home/ddp/clientdbts/siddhant_test/dbtrepo') directory.
PID 885571 stream output:
 [0m04:48:47  Running with dbt=1.6.6
PID 885571 stream output:
 [0m04:48:47  Registered adapter: postgres=1.6.6
PID 885571 stream output:
 [0m04:48:47  Encountered an error:
Compilation Error
  Model 'model.dbtrepo.diabetes3' (models/intermediate/diabetes3.sql) depends on a node named 'diabetes2' which was not found
Encountered exception during execution:
Traceback (most recent call last):
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect/engine.py", line 1733, in orchestrate_task_run
    result = await call.aresult()
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult
    return await asyncio.wrap_future(self.future)
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 315, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/tmp6p_0eiu3prefect/proxy/prefect_flows.py", line 111, in dbtjob_v1
    return dbt_op.run()
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 255, in coroutine_wrapper
    return call()
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 382, in __call__
    return self.result()
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 282, in result
    return self.future.result(timeout=timeout)
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 168, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 345, in _run_async
    result = await coro
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect_shell/commands.py", line 396, in run
    await shell_process.wait_for_completion()
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect_shell/commands.py", line 177, in wait_for_completion
    raise RuntimeError(
RuntimeError: PID 885571 failed with return code 2.
Finished in state Failed('Task run encountered an exception RuntimeError: PID 885571 failed with return code 2.')
Encountered exception during execution:
Traceback (most recent call last):
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect/engine.py", line 829, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult
    return await asyncio.wrap_future(self.future)
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 315, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/tmp6p_0eiu3prefect/proxy/prefect_flows.py", line 189, in deployment_schedule_flow_v4
  File "/tmp/tmp6p_0eiu3prefect/proxy/prefect_flows.py", line 111, in dbtjob_v1
    return dbt_op.run()
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 255, in coroutine_wrapper
    return call()
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 382, in __call__
    return self.result()
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 282, in result
    return self.future.result(timeout=timeout)
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 168, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 345, in _run_async
    result = await coro
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect_shell/commands.py", line 396, in run
    await shell_process.wait_for_completion()
  File "/home/ddp/prefect-proxy/venv/lib/python3.10/site-packages/prefect_shell/commands.py", line 177, in wait_for_completion
    raise RuntimeError(
RuntimeError: PID 885571 failed with return code 2.
Finished in state Failed('Flow run encountered an exception. RuntimeError: PID 885571 failed with return code 2.')
```

**Comment by siddhant3030** [comment]
@nairabhishek73 Please look at this

**Comment by nairabhishek73** [comment]
Hi Sid can you take a video of what you tried to do or describe the steps you took to recreate the error/bug and add a separate issue for coalesce.
@fatchat and @Ishankoradia consider this as an issue for errors. i.e. when a form is configured in such a way that it fails to create a table, the table in sid's screenshot is created, which is not helpful. No table should be created, or the text in the created table should say, "Error! Please check logs and reconfigure your function"

**Comment by fatchat** [comment]
@nairabhishek73 there are two nodes in the screenshot, are you referring to `diabetes3`

(also please call them nodes and not tables thanks)

"no node should be created" => this is not correct
"text in the created node should indicate an error" => yes this is the way we should do it... in the next release

the underlying error is that there is no table in the database corresponding to the model `diabetes2`. i looked at the repo on disk and i saw that the `diabetes2.sql` used to exist but doesn't any more, leading me to believe that a `DELETE` operation failed halfway (because the SQL was deleted but the model under the node was not)

**Comment by nairabhishek73** [comment]
Upon error we cannot have another table-node created with a suggestion to the user to hit run again as this is an incorrect suggestion which will leave the user in a loop. Moreover the chances of table creation errors are high and so this design created the possibiliyt of a frequent loop, which we should avoid in version 1.
We should update the text in that table-node to say "Error! Please check logs and/or reconfigure your function" for this release.

Moreover I do not see a user scenario where a table-node saying 'click on run to materialise your model' is required. It is not in the design or discussed. What was thought of when this was created?

**Comment by Ishankoradia** [comment]
- Empty tables that dont have cilumns fetched should show the message `Something went wrong. Please check logs`. In the logs window is empty, message should say `Please press run` 
-

**Comment by siddhant3030** [comment]
I think we can close this right?

**Comment by Ishankoradia** [comment]
@nairabhishek73 can we close this ?

**Comment by nairabhishek73** [comment]
Yes thanks
